import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import type { Dictionary, Transform } from 'style-dictionary/types';
import * as render from './formats.ts';
import { BuildError } from './formats.ts';
import {
  FONT_WEIGHTS,
  isRecord,
  readTokenFiles,
  validate,
} from './validate.ts';

export { BuildError };

export const DURATION = 'fossil/duration/css';
export const FONT_WEIGHT = 'fossil/fontWeight/css';

// Style Dictionary 5.5.5 leaves both of these as they are, which isn't valid CSS.
const TRANSFORM_HOOKS: Record<string, Omit<Transform, 'name'>> = {
  [DURATION]: {
    type: 'value',
    filter: (token) => token.$type === 'duration',
    transform: (token) => {
      const duration: unknown = token.$value;
      return isRecord(duration)
        ? `${String(duration.value)}${String(duration.unit)}`
        : duration;
    },
  },
  [FONT_WEIGHT]: {
    type: 'value',
    filter: (token) =>
      token.$type === 'fontWeight' && typeof token.$value === 'string',
    transform: (token) => {
      const name: unknown = token.$value;
      return FONT_WEIGHTS[String(name)] ?? name;
    },
  },
};

/** The CSS transforms, in order. */
export const TRANSFORMS = [
  'name/kebab',
  // Keeps a DTCG dimension's own unit: { value: 0.5, unit: "rem" } becomes 0.5rem.
  'size/rem',
  'color/css',
  'fontFamily/css',
  'cubicBezier/css',
  'strokeStyle/css/shorthand',
  'border/css/shorthand',
  'shadow/css/shorthand',
  DURATION,
  FONT_WEIGHT,
];

export interface BuildOptions {
  /** The token source folder, holding primitive/ and semantic/. */
  source: string;
  /** The package folder. Outputs go to dist/ and src/generated/ inside it. */
  root: string;
  /** The system name and CSS prefix from fossil.config.json. */
  name: string;
  prefix: string;
  /** The AGENTS.md whose foundations block the build replaces. */
  agents?: string;
  transforms?: readonly string[];
}

export interface BuildResult {
  tokens: number;
  files: string[];
}

/**
 * Validates the token source, runs Style Dictionary once, and writes every output.
 * Throws a BuildError, having written nothing, if any step fails.
 */
export async function build(options: BuildOptions): Promise<BuildResult> {
  const { tokens, problems } = validate(readTokenFiles(options.source));
  if (problems.length > 0)
    throw new BuildError(
      problems.map(
        (p) => `${p.file}${p.token ? ` › ${p.token}` : ''}: ${p.message}`,
      ),
    );

  const header = `${options.name} tokens, generated by the token build. Don't edit this file: change the token source.`;
  const entries = ({ allTokens }: Dictionary) => render.join(tokens, allTokens);
  const sd = new StyleDictionary({
    source: [join(options.source, '**/*.tokens.json')],
    log: { warnings: 'error', verbosity: 'silent' },
    hooks: {
      transforms: TRANSFORM_HOOKS,
      formats: {
        'fossil/css': ({ dictionary }) =>
          render.css(entries(dictionary), header),
        'fossil/json': ({ dictionary }) =>
          `${JSON.stringify(render.tokensFile(entries(dictionary)), null, 2)}\n`,
        'fossil/lint': ({ dictionary }) =>
          `${JSON.stringify(render.lintLists(entries(dictionary)), null, 2)}\n`,
        'fossil/keys': ({ dictionary }) =>
          render.tokenKeys(entries(dictionary), header),
        'fossil/breakpoints': ({ dictionary }) =>
          render.breakpoints(entries(dictionary), header),
        'fossil/css-types': () => render.declaration(),
        'fossil/json-types': () => render.declaration('TokensFile'),
        'fossil/lint-types': () => render.declaration('LintLists'),
        'fossil/foundations-md': ({ dictionary }) =>
          render.foundationsMarkdown(
            render.tokensFile(entries(dictionary)),
            options.prefix,
            header,
          ),
        'fossil/foundations-brief': ({ dictionary }) =>
          render.foundationsBrief(
            render.tokensFile(entries(dictionary)),
            header,
          ),
        'fossil/reference': ({ dictionary }) =>
          render.tokenReference(render.tokensFile(entries(dictionary)), header),
        'fossil/foundations': ({ dictionary }) =>
          render.foundations(
            render.tokensFile(entries(dictionary)),
            options.prefix,
          ),
      },
    },
    platforms: {
      web: {
        prefix: options.prefix,
        transforms: [...(options.transforms ?? TRANSFORMS)],
        // Typography becomes one custom property per part. The font shorthand would drop letter-spacing.
        expand: { include: ['typography'] },
        files: [
          { destination: 'dist/tokens.css', format: 'fossil/css' },
          { destination: 'dist/tokens.css.d.ts', format: 'fossil/css-types' },
          { destination: 'dist/tokens.json', format: 'fossil/json' },
          {
            destination: 'dist/tokens.json.d.cts',
            format: 'fossil/json-types',
          },
          { destination: 'dist/lint.json', format: 'fossil/lint' },
          {
            destination: 'dist/foundations.md',
            format: 'fossil/foundations-md',
          },
          {
            destination: 'dist/foundations-brief.md',
            format: 'fossil/foundations-brief',
          },
          { destination: 'dist/tokens.md', format: 'fossil/reference' },
          { destination: 'dist/lint.json.d.cts', format: 'fossil/lint-types' },
          { destination: 'src/generated/tokens.ts', format: 'fossil/keys' },
          {
            destination: 'src/generated/breakpoints.ts',
            format: 'fossil/breakpoints',
          },
          { destination: 'AGENTS.md', format: 'fossil/foundations' },
        ],
      },
    },
  });
  // Fossil's checks name the tokens involved, so they run before Style Dictionary's own.
  render.join(tokens, (await sd.getPlatformTokens('web')).allTokens);
  // Formats in memory, so nothing is written unless every output is valid.
  const outputs = await sd.formatPlatform('web');

  const files: string[] = [];
  let agents: string | undefined;
  if (options.agents !== undefined) {
    const block = outputs.find((o) => o.destination === 'AGENTS.md');
    const current = readFileSync(options.agents, 'utf8');
    const next = render.replaceBlock(current, String(block?.output));
    if (next !== current) agents = next;
  }
  rmSync(join(options.root, 'dist'), { recursive: true, force: true });
  rmSync(join(options.root, 'src/generated'), { recursive: true, force: true });
  for (const { destination, output } of outputs) {
    if (destination === undefined || destination === 'AGENTS.md') continue;
    const file = join(options.root, destination);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, String(output));
    files.push(destination);
  }
  if (options.agents !== undefined && agents !== undefined) {
    writeFileSync(options.agents, agents);
    files.push('AGENTS.md');
  }
  return { tokens: tokens.length, files };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const repo = new URL('../../../', import.meta.url);
  const config = JSON.parse(
    readFileSync(new URL('fossil.config.json', repo), 'utf8'),
  ) as { name: string; cssPrefix: string };
  try {
    const { tokens, files } = await build({
      source: fileURLToPath(new URL('../src', import.meta.url)),
      root: fileURLToPath(new URL('..', import.meta.url)),
      name: config.name,
      prefix: config.cssPrefix,
      agents: fileURLToPath(new URL('AGENTS.md', repo)),
    });
    console.log(`Built ${String(tokens)} tokens into ${files.join(', ')}.`);
  } catch (error) {
    if (!(error instanceof BuildError)) throw error;
    for (const problem of error.problems) console.error(`✗ ${problem}`);
    const count = error.problems.length;
    console.error(
      `\n${String(count)} problem${count === 1 ? '' : 's'}. Nothing was built.`,
    );
    process.exit(1);
  }
}
